// <auto-generated />
using System;
using Kolokwium_2.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolokwium_2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250613123454_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolokwium_2.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artist");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            BirthDate = new DateTime(1999, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Franek",
                            LastName = "Zak"
                        },
                        new
                        {
                            ArtistId = 2,
                            BirthDate = new DateTime(1899, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lui",
                            LastName = "Wolo"
                        },
                        new
                        {
                            ArtistId = 3,
                            BirthDate = new DateTime(1939, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sashka",
                            LastName = "Bicepsik"
                        });
                });

            modelBuilder.Entity("Kolokwium_2.Models.Artwork", b =>
                {
                    b.Property<int>("ArtworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtworkId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YearCreated")
                        .HasColumnType("int");

                    b.HasKey("ArtworkId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Artwork");

                    b.HasData(
                        new
                        {
                            ArtworkId = 1,
                            ArtistId = 1,
                            Title = "Jozin Zbazin",
                            YearCreated = 2012
                        },
                        new
                        {
                            ArtworkId = 2,
                            ArtistId = 1,
                            Title = "Jo Zbazin",
                            YearCreated = 2020
                        },
                        new
                        {
                            ArtworkId = 3,
                            ArtistId = 2,
                            Title = "in",
                            YearCreated = 1912
                        },
                        new
                        {
                            ArtworkId = 4,
                            ArtistId = 3,
                            Title = "Zuch",
                            YearCreated = 1979
                        });
                });

            modelBuilder.Entity("Kolokwium_2.Models.Exhibition", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExhibitionId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GalleryId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfArtworks")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ExhibitionId");

                    b.HasIndex("GalleryId");

                    b.ToTable("Exhibition");

                    b.HasData(
                        new
                        {
                            ExhibitionId = 1,
                            GalleryId = 1,
                            NumberOfArtworks = 3,
                            StartDate = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Choroszcza"
                        },
                        new
                        {
                            ExhibitionId = 2,
                            EndDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 2,
                            NumberOfArtworks = 10,
                            StartDate = new DateTime(2023, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sock"
                        });
                });

            modelBuilder.Entity("Kolokwium_2.Models.ExhibitionArtwork", b =>
                {
                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<int>("ExhibitionId")
                        .HasColumnType("int");

                    b.Property<decimal>("InsuranceValue")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ArtworkId", "ExhibitionId");

                    b.HasIndex("ExhibitionId");

                    b.ToTable("ExhibitionArtwork");

                    b.HasData(
                        new
                        {
                            ArtworkId = 1,
                            ExhibitionId = 1,
                            InsuranceValue = 12m
                        },
                        new
                        {
                            ArtworkId = 2,
                            ExhibitionId = 1,
                            InsuranceValue = 24m
                        },
                        new
                        {
                            ArtworkId = 3,
                            ExhibitionId = 2,
                            InsuranceValue = 55m
                        },
                        new
                        {
                            ArtworkId = 1,
                            ExhibitionId = 2,
                            InsuranceValue = 123m
                        });
                });

            modelBuilder.Entity("Kolokwium_2.Models.Gallery", b =>
                {
                    b.Property<int>("GalleryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GalleryId"));

                    b.Property<DateTime>("EstablishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GalleryId");

                    b.ToTable("Gallery");

                    b.HasData(
                        new
                        {
                            GalleryId = 1,
                            EstablishedDate = new DateTime(1324, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bydgoszcz"
                        },
                        new
                        {
                            GalleryId = 2,
                            EstablishedDate = new DateTime(1132, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Siedlckie muzeum prawie diecezjalne"
                        });
                });

            modelBuilder.Entity("Kolokwium_2.Models.Artwork", b =>
                {
                    b.HasOne("Kolokwium_2.Models.Artist", "Artist")
                        .WithMany("Artworks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Kolokwium_2.Models.Exhibition", b =>
                {
                    b.HasOne("Kolokwium_2.Models.Gallery", "Gallery")
                        .WithMany("Exhibitions")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("Kolokwium_2.Models.ExhibitionArtwork", b =>
                {
                    b.HasOne("Kolokwium_2.Models.Artwork", "Artwork")
                        .WithMany("ExhibitionArtworks")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium_2.Models.Exhibition", "Exhibition")
                        .WithMany("ExhibitionArtworks")
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Exhibition");
                });

            modelBuilder.Entity("Kolokwium_2.Models.Artist", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("Kolokwium_2.Models.Artwork", b =>
                {
                    b.Navigation("ExhibitionArtworks");
                });

            modelBuilder.Entity("Kolokwium_2.Models.Exhibition", b =>
                {
                    b.Navigation("ExhibitionArtworks");
                });

            modelBuilder.Entity("Kolokwium_2.Models.Gallery", b =>
                {
                    b.Navigation("Exhibitions");
                });
#pragma warning restore 612, 618
        }
    }
}
